#### 1. Crea un arrays lleno de 1s con una logitud dada por el usuario.

In [2]:
# importar modulos
import numpy as np

longitud = int(input("Ingrese la longitud del array: "))

# Crear un array de longitud n con valores 1
array_ones = np.ones(longitud)

print(array_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 2. Cambia la forma del array para que tenga una estructura de tipo (filas, columnas).

In [5]:
#importar modulos
import numpy as np

longitud = int(input("Ingrese la longitud del array: "))

# Crear un array de longitud n con valores 1
array_ones = np.ones(longitud)
print(array_ones)

# Pediendo al usuario la nueva forma del array
filas = int(input("Ingrese el número de filas: "))
columnas = int(input("Ingrese el número de columnas: "))

# comprobamos que el reshape sea posible
if filas * columnas == longitud:
    # Cambiar la forma del array (reshape)
    nuevo_array = array_ones.reshape(filas, columnas)
    print(nuevo_array)
else:
    # indicamos que el producto de filas y columnas no es igual a la longitud del array
    print("La cantidad de filas y columnas no es compatible con la longitud del array")




[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 3. Crea una matriz identidad con la misma forma que el array anterior.

In [6]:
#importar modulos
import numpy as np

longitud = int(input("Ingrese la longitud del array: "))

# Crear un array de longitud n con valores 1
array_ones = np.ones(longitud)
print(array_ones)

# Pediendo al usuario la nueva forma del array
filas = int(input("Ingrese el número de filas: "))
columnas = int(input("Ingrese el número de columnas: "))

# comprobamos que el reshape sea posible
if filas * columnas == longitud:
    # Cambiar la forma del array (reshape)
    nuevo_array = array_ones.reshape(filas, columnas)
    print("Array con nueva forma: \n", nuevo_array)
    # Crear una matriz identidad de eye(filas, columnas)
    matriz_indentidad = np.eye(filas, columnas)
    print("Matriz identidad \n", matriz_indentidad)
else:
    # indicamos que el producto de filas y columnas no es igual a la longitud del array
    print("La cantidad de filas y columnas no es compatible con la longitud del array")

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array con nueva forma: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matriz identidad 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
