#### 1. Crea un array con 15 números enteros aleatorios entre 1 y 100

In [1]:
# importar modulos necesarios
import numpy as np

array_random = np.random.randint(1, 101, size=15)

print(array_random)



[29 25 73 75 27 63 40 88 29 10 83 48 54 34 66]


#### 2. Multiplica todos los elementos del array usando un bucle y después usando un método de numpy. Compara los resultados.

In [7]:
# importar modulos necesarios
import numpy as np

# creamos array con numeros aleatorios entre el 1 y el 100
array_random = np.random.randint(1, 101, size=15)
print(array_random)

multi_bucle = 1
# Multiplicacion usando un bucle
for numero in array_random:
    multi_bucle = multi_bucle * numero

print("Multiplicacion con bucle: ", multi_bucle)

# Multiplicacion usando la funcion prod de numpy
multi_numpy = np.prod(array_random)
print("Multiplicacion con numpy: ", multi_numpy)


[ 68  62  19 100  75  58   6  71  22  18   1  43  12  80   8]
Multiplicacion con bucle:  4326013209386680320
Multiplicacion con numpy:  4326013209386680320


/tmp/ipykernel_6777/3123804653.py:11: RuntimeWarning: overflow encountered in scalar multiply
  multi_bucle = multi_bucle * numero


#### 3. Crea otro array con 15 números decimales aleatorios entre 0 y 1

In [12]:
# importar modulos necesarios
import numpy as np

# creamos array con numeros aleatorios entre el 0 y el 1

array_random = np.random.random(15)

print(array_random)


[0.97113699 0.9724788  0.84667352 0.6435315  0.44265838 0.53695792
 0.46653369 0.19987629 0.05333323 0.53622319 0.64741237 0.14559878
 0.26941638 0.61657208 0.93412227]


#### 4. Suma los elementos de ambos arrays elemento por elemento. Resuélvelo usando un operador y después usando un método de numpy. Compara los resultados.

In [16]:
# importar modulos necesarios
import numpy as np

array_random = np.random.randint(1, 101, size=15)
array_decimales = np.random.random(15)

print("Array Random:", array_random)
print("Array Decimales:", array_decimales)

# Suma de los dos arrays usando operador

suma_operador = array_random + array_decimales
print("Suma con operador: ", suma_operador)

# Suma de los dos arrays usando la funcion add de numpy
suma_numpy = np.add(array_random, array_decimales)
print("Suma con numpy: ", suma_numpy)

Array Random: [11  4  5 47 43 38 30 75 38 38 93 19 82 30 77]
Array Decimales: [0.18933458 0.2286583  0.70830082 0.28458946 0.9357786  0.39234178
 0.65969682 0.49101927 0.71030251 0.45353043 0.16065654 0.69464356
 0.75500103 0.98162798 0.44850749]
Suma con operador:  [11.18933458  4.2286583   5.70830082 47.28458946 43.9357786  38.39234178
 30.65969682 75.49101927 38.71030251 38.45353043 93.16065654 19.69464356
 82.75500103 30.98162798 77.44850749]
Suma con numpy:  [11.18933458  4.2286583   5.70830082 47.28458946 43.9357786  38.39234178
 30.65969682 75.49101927 38.71030251 38.45353043 93.16065654 19.69464356
 82.75500103 30.98162798 77.44850749]


#### 5. Ahora réstalos. Resuélvelo usando un operador y después usando un método de numpy. Compara los resultados.

In [1]:
# importar modulos necesarios
import numpy as np

array_random = np.random.randint(1, 101, size=15)
array_decimales = np.random.random(15)

print("Array Random:", array_random)
print("Array Decimales:", array_decimales)

# Resta de los dos arrays usando operador

resta_operador = array_random - array_decimales
print("Resta con operador: ", resta_operador)

# Resta de los dos arrays usando la funcion subtract de numpy
resta_numpy = np.subtract(array_random, array_decimales)
print("Resta con numpy: ", resta_numpy)


Array Random: [95 48 49 45 71 66 71  8 95  4  2 98 12 44 35]
Array Decimales: [0.43237017 0.78178033 0.36926075 0.18814622 0.01909709 0.62211552
 0.70413175 0.8916387  0.1921365  0.64934696 0.52435432 0.29504943
 0.40093722 0.51207945 0.14372421]
Resta con operador:  [94.56762983 47.21821967 48.63073925 44.81185378 70.98090291 65.37788448
 70.29586825  7.1083613  94.8078635   3.35065304  1.47564568 97.70495057
 11.59906278 43.48792055 34.85627579]
Resta con numpy:  [94.56762983 47.21821967 48.63073925 44.81185378 70.98090291 65.37788448
 70.29586825  7.1083613  94.8078635   3.35065304  1.47564568 97.70495057
 11.59906278 43.48792055 34.85627579]


#### 6. Haz lo mismo con la multiplicación elemento por elemento. Usa un operador y después con una función de numpy.

In [2]:
# importar modulos necesarios
import numpy as np

array_random = np.random.randint(1, 101, size=15)
array_decimales = np.random.random(15)

# Multiplicacion de los dos arrays usando operador
multiplicacion_operador = array_random * array_decimales
print("Multiplicación con operador: ", multiplicacion_operador)

# Multiplicacion de los dos arrays usando la funcion multiply de numpy
multiplicacion_numpy = np.multiply(array_random, array_decimales)
print("Multiplicación con numpy: ", multiplicacion_numpy)




Multiplicación con operador:  [ 9.99968829 14.4129415   5.92545786  7.00965346 62.23636841  2.97419853
  6.37046723 23.09946836 25.94131067 29.21452698 47.70191447  0.27682254
 39.68779822 28.13321926 13.01467905]
Multiplicación con numpy:  [ 9.99968829 14.4129415   5.92545786  7.00965346 62.23636841  2.97419853
  6.37046723 23.09946836 25.94131067 29.21452698 47.70191447  0.27682254
 39.68779822 28.13321926 13.01467905]


#### 6.1 Realiza la division con el operador y con una funcion de numpy.

In [ ]:
# importar modulos necesarios
import numpy as np

array_random = np.random.randint(1, 101, size=15)
array_decimales = np.random.random(15)

# Division de los dos arrays usando operador
division_operador = array_random / array_decimales
print("Division con operador: ", division_operador)

# Division de los dos arrays usando la funcion divide de numpy
division_numpy = np.divide(array_random, array_decimales)
print("Division con numpy: ", division_numpy)

#### 7. Encuentra el valor máximo de cada array y el valor minimo de cada array.

In [4]:
# importar modulos necesarios
import numpy as np

array_random = np.random.randint(1, 101, size=15)

print(array_random)

# Calculamos la media de los elementos del array
media = np.mean(array_random)
print(f"Media: {media:.2f}")

# Calculamos el valor maximo del array
maximo = np.max(array_random)
print("Maximo: ", maximo)

# Calculamos el valor minimo del array
minimo = np.min(array_random)
print("Minimo: ", minimo)


[60 82 24 36 74 67 40 55  4 71 53 27 77 53 51]
Media: 51.60
Maximo:  82
Minimo:  4


#### 8. Calcula la media (mean), la mediana (median), la desviación estandar (std) y la varianza (var) de cada array.

In [6]:
# importar modulos necesarios
import numpy as np

#creamos array
array_random = np.random.randint(1, 101, size=15)
array_decimales = np.random.random(15)
print("Array Random:", array_random)
print("Array Decimales:", array_decimales)

# Calculamos la media de los elementos del array
media_random = np.mean(array_random)
media_decimales = np.mean(array_decimales)

print(f"Media Random: {media:.2f}")
print(f"Media Decimales: {media:.2f}")


# Calculamos la mediana de los arrays
mediana_random = np.median(array_random)
mediana_decimales = np.median(array_decimales)

print("Mediana Array Random: ", mediana_random)
print("Mediana Array Decimales: ", mediana_decimales)

# Calculamos la desviacion estandar de los arrays
desviacion_random = np.std(array_random)
desviacion_decimales = np.std(array_decimales)

print(f"Desviacion estandar Array Random: {desviacion_random:.2f}")
print(f"Desviacion estandar Array Decimales: {desviacion_decimales:.2f}")

# Calculamos la varianza de los arrays
varianza_random = np.var(array_random)
varianza_decimales = np.var(array_decimales)

print(f"Varianza Array Random: {varianza_random:.2f}")
print(f"Varianza Array Decimales: {varianza_decimales:.2f}")





Array Random: [67 15 17 62 52 20 27 67 81  8  4 88 64 47 33]
Array Decimales: [0.72030664 0.2122955  0.61523355 0.16931665 0.97400896 0.52232702
 0.48258802 0.4007092  0.82732289 0.97876866 0.43138933 0.96670092
 0.26433491 0.18341677 0.50408619]
Media Random: 45.67
Media Decimales: 45.67
Mediana Array Random:  47.0
Mediana Array Decimales:  0.5040861923496899
Desviacion estandar Array Random: 26.59
Desviacion estandar Array Decimales: 0.28
Varianza Array Random: 707.18
Varianza Array Decimales: 0.08
