1. Crea un array_1 lleno de 0s de tamaño 8

In [2]:
#realizar los imports necesarios
import numpy as np

# crear array
array_1 = np.zeros(8)
print(array_1)


[0. 0. 0. 0. 0. 0. 0. 0.]


2. Haz que todos los elementos de este array sean igual a 2

In [3]:
#realizar los imports necesarios
import numpy as np

# crear array
array_1 = np.zeros(8)
print("array original",array_1)

# cambiar valores a 2
array_1[:] = 2
print("array modificado",array_1)

array original [0. 0. 0. 0. 0. 0. 0. 0.]
array modificado [2. 2. 2. 2. 2. 2. 2. 2.]


### 3 Crea un array_2 que contenga todos los numeros pares del 1 al 10



In [4]:
import numpy as np

# creamos el array 
array_2 = np.arange(2,11,2)
print(array_2)


[ 2  4  6  8 10]


### 4. Suma todos los elementos de array_2 usando un bucle y después usando la función sum()


In [4]:
import numpy as np

# creamos el array 
array_2 = np.arange(2,11,2)

# sumar elementos usando un bucle
suma_bucle = 0
for numero in array_2:
    suma_bucle += numero
print("suma con bucle",suma_bucle)

#sumar usando Numpy
suma_numpy = np.sum(array_2)
print("suma con numpy",suma_numpy)

# comparar los resultados
if suma_bucle == suma_numpy:
    print("Los resultados son iguales")
else:
    print("Los resultados son diferentes")



suma con bucle 30
suma con numpy 30
Los resultados son iguales


5. revierte array_2 y guárdalo en una variable independiente.

In [8]:
import numpy as np

array_2 = np.arange(2,11,2)
print("array original",array_2)

# definir array_2_revertido [:] hace que se cree un array independiente
array_2_revertido[:] = array_2[::-1]

# creamos array revertido independiente
array_2_revertido[:] = array_2[::-1]
print("Array revertido", array_2_revertido)

# comprobamos que son independientes
# cambiar valores a 2
array_2_revertido[:] = 2
print("Array revertido nuevo", array_2_revertido)
print("Array original nuevo", array_2)


array original [ 2  4  6  8 10]
Array revertido [10  8  6  4  2]
Array revertido nuevo [2 2 2 2 2]
Array original nuevo [ 2  4  6  8 10]


6. Encuentra los elementos comunes entre array_1 y array_2 y entre array_2 y array_2_invertido

In [4]:
import numpy as np

# creamos el array
array_2 = np.arange(2, 11, 2)
array_2_revertido = array_2[::-1].copy()  # Definimos array_2_revertido como una copia independiente de array_2
array_1 = np.zeros(8)
array_1[:] = 2

print(array_1)
print(array_2)
print(array_2_revertido)

# intersectar arrays con array_1 y array_2

interseccion_1 = np.intersect1d(array_1, array_2)
print("Elementos comunes entre array_1 y array_2:", interseccion_1) 

# intersectar arrays con array_1 y array_2_revertido

interseccion_2 = np.intersect1d(array_1, array_2_revertido)
print("Elementos comunes entre array_1 y array_2_revertido:", interseccion_2) 


[2. 2. 2. 2. 2. 2. 2. 2.]
[ 2  4  6  8 10]
[10  8  6  4  2]
Elementos comunes entre array_1 y array_2: [2.]
Elementos comunes entre array_1 y array_2_revertido: [2.]
